name = "dashboard-licenciamento"
type = "javascript"
main = "src/index.js"

[env.production]
name = "dashboard-licenciamento"

[[d1_databases]]
binding = "DB"
database_name = "dashboard-licenciamento-db"
database_id = "TBD"
